# run after build to remove unused SVG files from Ionicons and .DS_Store files

# currently used Ionicons
# rm ./www/svg/logo-github.svg
# rm ./www/svg/mail-outline.svg
# rm ./www/svg/warning-outline.svg
# rm ./www/svg/close.svg
# rm ./www/svg/close-circle.svg
# rm ./www/svg/close-circle-outline.svg
# rm ./www/svg/chevron-up-outline.svg
# rm ./www/svg/chevron-down-outline.svg
# rm ./www/svg/checkmark-circle-outline.svg
# rm ./www/svg/menu-outline.svg
# rm ./www/svg/menu-sharp.svg
# rm ./www/svg/menu.svg
# rm ./www/svg/search-outline.svg
# rm ./www/svg/information-circle-outline.svg

find "./www" -name ".DS_Store" -type f -o -name ".DS_Store" -type d

rm ./www/svg/add-circle-outline.svg
rm ./www/svg/add-circle-sharp.svg
rm ./www/svg/add-circle.svg
rm ./www/svg/add-outline.svg
rm ./www/svg/add-sharp.svg
rm ./www/svg/add.svg
rm ./www/svg/airplane-outline.svg
rm ./www/svg/airplane-sharp.svg
rm ./www/svg/airplane.svg
rm ./www/svg/alarm-outline.svg
rm ./www/svg/alarm-sharp.svg
rm ./www/svg/alarm.svg
rm ./www/svg/albums-outline.svg
rm ./www/svg/albums-sharp.svg
rm ./www/svg/albums.svg
rm ./www/svg/alert-circle-outline.svg
rm ./www/svg/alert-circle-sharp.svg
rm ./www/svg/alert-circle.svg
rm ./www/svg/alert-outline.svg
rm ./www/svg/alert-sharp.svg
rm ./www/svg/alert.svg
rm ./www/svg/american-football-outline.svg
rm ./www/svg/american-football-sharp.svg
rm ./www/svg/american-football.svg
rm ./www/svg/analytics-outline.svg
rm ./www/svg/analytics-sharp.svg
rm ./www/svg/analytics.svg
rm ./www/svg/aperture-outline.svg
rm ./www/svg/aperture-sharp.svg
rm ./www/svg/aperture.svg
rm ./www/svg/apps-outline.svg
rm ./www/svg/apps-sharp.svg
rm ./www/svg/apps.svg
rm ./www/svg/archive-outline.svg
rm ./www/svg/archive-sharp.svg
rm ./www/svg/archive.svg
rm ./www/svg/arrow-back-circle-outline.svg
rm ./www/svg/arrow-back-circle-sharp.svg
rm ./www/svg/arrow-back-circle.svg
rm ./www/svg/arrow-back-outline.svg
rm ./www/svg/arrow-back-sharp.svg
rm ./www/svg/arrow-back.svg
rm ./www/svg/arrow-down-circle-outline.svg
rm ./www/svg/arrow-down-circle-sharp.svg
rm ./www/svg/arrow-down-circle.svg
rm ./www/svg/arrow-down-outline.svg
rm ./www/svg/arrow-down-sharp.svg
rm ./www/svg/arrow-down.svg
rm ./www/svg/arrow-forward-circle-outline.svg
rm ./www/svg/arrow-forward-circle-sharp.svg
rm ./www/svg/arrow-forward-circle.svg
rm ./www/svg/arrow-forward-outline.svg
rm ./www/svg/arrow-forward-sharp.svg
rm ./www/svg/arrow-forward.svg
rm ./www/svg/arrow-redo-circle-outline.svg
rm ./www/svg/arrow-redo-circle-sharp.svg
rm ./www/svg/arrow-redo-circle.svg
rm ./www/svg/arrow-redo-outline.svg
rm ./www/svg/arrow-redo-sharp.svg
rm ./www/svg/arrow-redo.svg
rm ./www/svg/arrow-undo-circle-outline.svg
rm ./www/svg/arrow-undo-circle-sharp.svg
rm ./www/svg/arrow-undo-circle.svg
rm ./www/svg/arrow-undo-outline.svg
rm ./www/svg/arrow-undo-sharp.svg
rm ./www/svg/arrow-undo.svg
rm ./www/svg/arrow-up-circle-outline.svg
rm ./www/svg/arrow-up-circle-sharp.svg
rm ./www/svg/arrow-up-circle.svg
rm ./www/svg/arrow-up-outline.svg
rm ./www/svg/arrow-up-sharp.svg
rm ./www/svg/arrow-up.svg
rm ./www/svg/at-circle-outline.svg
rm ./www/svg/at-circle-sharp.svg
rm ./www/svg/at-circle.svg
rm ./www/svg/at-outline.svg
rm ./www/svg/at-sharp.svg
rm ./www/svg/at.svg
rm ./www/svg/attach-outline.svg
rm ./www/svg/attach-sharp.svg
rm ./www/svg/attach.svg
rm ./www/svg/backspace-outline.svg
rm ./www/svg/backspace-sharp.svg
rm ./www/svg/backspace.svg
rm ./www/svg/bandage-outline.svg
rm ./www/svg/bandage-sharp.svg
rm ./www/svg/bandage.svg
rm ./www/svg/bar-chart-outline.svg
rm ./www/svg/bar-chart-sharp.svg
rm ./www/svg/bar-chart.svg
rm ./www/svg/barbell-outline.svg
rm ./www/svg/barbell-sharp.svg
rm ./www/svg/barbell.svg
rm ./www/svg/barcode-outline.svg
rm ./www/svg/barcode-sharp.svg
rm ./www/svg/barcode.svg
rm ./www/svg/baseball-outline.svg
rm ./www/svg/baseball-sharp.svg
rm ./www/svg/baseball.svg
rm ./www/svg/basket-outline.svg
rm ./www/svg/basket-sharp.svg
rm ./www/svg/basket.svg
rm ./www/svg/basketball-outline.svg
rm ./www/svg/basketball-sharp.svg
rm ./www/svg/basketball.svg
rm ./www/svg/battery-charging-outline.svg
rm ./www/svg/battery-charging-sharp.svg
rm ./www/svg/battery-charging.svg
rm ./www/svg/battery-dead-outline.svg
rm ./www/svg/battery-dead-sharp.svg
rm ./www/svg/battery-dead.svg
rm ./www/svg/battery-full-outline.svg
rm ./www/svg/battery-full-sharp.svg
rm ./www/svg/battery-full.svg
rm ./www/svg/battery-half-outline.svg
rm ./www/svg/battery-half-sharp.svg
rm ./www/svg/battery-half.svg
rm ./www/svg/beaker-outline.svg
rm ./www/svg/beaker-sharp.svg
rm ./www/svg/beaker.svg
rm ./www/svg/bed-outline.svg
rm ./www/svg/bed-sharp.svg
rm ./www/svg/bed.svg
rm ./www/svg/beer-outline.svg
rm ./www/svg/beer-sharp.svg
rm ./www/svg/beer.svg
rm ./www/svg/bicycle-outline.svg
rm ./www/svg/bicycle-sharp.svg
rm ./www/svg/bicycle.svg
rm ./www/svg/bluetooth-outline.svg
rm ./www/svg/bluetooth-sharp.svg
rm ./www/svg/bluetooth.svg
rm ./www/svg/boat-outline.svg
rm ./www/svg/boat-sharp.svg
rm ./www/svg/boat.svg
rm ./www/svg/body-outline.svg
rm ./www/svg/body-sharp.svg
rm ./www/svg/body.svg
rm ./www/svg/bonfire-outline.svg
rm ./www/svg/bonfire-sharp.svg
rm ./www/svg/bonfire.svg
rm ./www/svg/book-outline.svg
rm ./www/svg/book-sharp.svg
rm ./www/svg/book.svg
rm ./www/svg/bookmark-outline.svg
rm ./www/svg/bookmark-sharp.svg
rm ./www/svg/bookmark.svg
rm ./www/svg/bookmarks-outline.svg
rm ./www/svg/bookmarks-sharp.svg
rm ./www/svg/bookmarks.svg
rm ./www/svg/briefcase-outline.svg
rm ./www/svg/briefcase-sharp.svg
rm ./www/svg/briefcase.svg
rm ./www/svg/browsers-outline.svg
rm ./www/svg/browsers-sharp.svg
rm ./www/svg/browsers.svg
rm ./www/svg/brush-outline.svg
rm ./www/svg/brush-sharp.svg
rm ./www/svg/brush.svg
rm ./www/svg/bug-outline.svg
rm ./www/svg/bug-sharp.svg
rm ./www/svg/bug.svg
rm ./www/svg/build-outline.svg
rm ./www/svg/build-sharp.svg
rm ./www/svg/build.svg
rm ./www/svg/bulb-outline.svg
rm ./www/svg/bulb-sharp.svg
rm ./www/svg/bulb.svg
rm ./www/svg/bus-outline.svg
rm ./www/svg/bus-sharp.svg
rm ./www/svg/bus.svg
rm ./www/svg/business-outline.svg
rm ./www/svg/business-sharp.svg
rm ./www/svg/business.svg
rm ./www/svg/cafe-outline.svg
rm ./www/svg/cafe-sharp.svg
rm ./www/svg/cafe.svg
rm ./www/svg/calculator-outline.svg
rm ./www/svg/calculator-sharp.svg
rm ./www/svg/calculator.svg
rm ./www/svg/calendar-outline.svg
rm ./www/svg/calendar-sharp.svg
rm ./www/svg/calendar.svg
rm ./www/svg/call-outline.svg
rm ./www/svg/call-sharp.svg
rm ./www/svg/call.svg
rm ./www/svg/camera-outline.svg
rm ./www/svg/camera-reverse-outline.svg
rm ./www/svg/camera-reverse-sharp.svg
rm ./www/svg/camera-reverse.svg
rm ./www/svg/camera-sharp.svg
rm ./www/svg/camera.svg
rm ./www/svg/car-outline.svg
rm ./www/svg/car-sharp.svg
rm ./www/svg/car-sport-outline.svg
rm ./www/svg/car-sport-sharp.svg
rm ./www/svg/car-sport.svg
rm ./www/svg/car.svg
rm ./www/svg/card-outline.svg
rm ./www/svg/card-sharp.svg
rm ./www/svg/card.svg
rm ./www/svg/caret-back-circle-outline.svg
rm ./www/svg/caret-back-circle-sharp.svg
rm ./www/svg/caret-back-circle.svg
rm ./www/svg/caret-back-outline.svg
rm ./www/svg/caret-back-sharp.svg
rm ./www/svg/caret-back.svg
rm ./www/svg/caret-down-circle-outline.svg
rm ./www/svg/caret-down-circle-sharp.svg
rm ./www/svg/caret-down-circle.svg
rm ./www/svg/caret-down-outline.svg
rm ./www/svg/caret-down-sharp.svg
rm ./www/svg/caret-down.svg
rm ./www/svg/caret-forward-circle-outline.svg
rm ./www/svg/caret-forward-circle-sharp.svg
rm ./www/svg/caret-forward-circle.svg
rm ./www/svg/caret-forward-outline.svg
rm ./www/svg/caret-forward-sharp.svg
rm ./www/svg/caret-forward.svg
rm ./www/svg/caret-up-circle-outline.svg
rm ./www/svg/caret-up-circle-sharp.svg
rm ./www/svg/caret-up-circle.svg
rm ./www/svg/caret-up-outline.svg
rm ./www/svg/caret-up-sharp.svg
rm ./www/svg/caret-up.svg
rm ./www/svg/cart-outline.svg
rm ./www/svg/cart-sharp.svg
rm ./www/svg/cart.svg
rm ./www/svg/cash-outline.svg
rm ./www/svg/cash-sharp.svg
rm ./www/svg/cash.svg
rm ./www/svg/cellular-outline.svg
rm ./www/svg/cellular-sharp.svg
rm ./www/svg/cellular.svg
rm ./www/svg/chatbox-ellipses-outline.svg
rm ./www/svg/chatbox-ellipses-sharp.svg
rm ./www/svg/chatbox-ellipses.svg
rm ./www/svg/chatbox-outline.svg
rm ./www/svg/chatbox-sharp.svg
rm ./www/svg/chatbox.svg
rm ./www/svg/chatbubble-ellipses-outline.svg
rm ./www/svg/chatbubble-ellipses-sharp.svg
rm ./www/svg/chatbubble-ellipses.svg
rm ./www/svg/chatbubble-outline.svg
rm ./www/svg/chatbubble-sharp.svg
rm ./www/svg/chatbubble.svg
rm ./www/svg/chatbubbles-outline.svg
rm ./www/svg/chatbubbles-sharp.svg
rm ./www/svg/chatbubbles.svg
rm ./www/svg/checkbox-outline.svg
rm ./www/svg/checkbox-sharp.svg
rm ./www/svg/checkbox.svg
rm ./www/svg/checkmark-circle-sharp.svg
rm ./www/svg/checkmark-circle.svg
rm ./www/svg/checkmark-done-circle-outline.svg
rm ./www/svg/checkmark-done-circle-sharp.svg
rm ./www/svg/checkmark-done-circle.svg
rm ./www/svg/checkmark-done-outline.svg
rm ./www/svg/checkmark-done-sharp.svg
rm ./www/svg/checkmark-done.svg
rm ./www/svg/checkmark-outline.svg
rm ./www/svg/checkmark-sharp.svg
rm ./www/svg/checkmark.svg
rm ./www/svg/chevron-back-circle-outline.svg
rm ./www/svg/chevron-back-circle-sharp.svg
rm ./www/svg/chevron-back-circle.svg
rm ./www/svg/chevron-back-outline.svg
rm ./www/svg/chevron-back-sharp.svg
rm ./www/svg/chevron-back.svg
rm ./www/svg/chevron-down-circle-outline.svg
rm ./www/svg/chevron-down-circle-sharp.svg
rm ./www/svg/chevron-down-circle.svg
rm ./www/svg/chevron-down-sharp.svg
rm ./www/svg/chevron-down.svg
rm ./www/svg/chevron-forward-circle-outline.svg
rm ./www/svg/chevron-forward-circle-sharp.svg
rm ./www/svg/chevron-forward-circle.svg
rm ./www/svg/chevron-forward-outline.svg
rm ./www/svg/chevron-forward-sharp.svg
rm ./www/svg/chevron-forward.svg
rm ./www/svg/chevron-up-circle-outline.svg
rm ./www/svg/chevron-up-circle-sharp.svg
rm ./www/svg/chevron-up-circle.svg
rm ./www/svg/chevron-up-sharp.svg
rm ./www/svg/chevron-up.svg
rm ./www/svg/clipboard-outline.svg
rm ./www/svg/clipboard-sharp.svg
rm ./www/svg/clipboard.svg
rm ./www/svg/close-circle-sharp.svg
rm ./www/svg/close-outline.svg
rm ./www/svg/close-sharp.svg
rm ./www/svg/cloud-circle-outline.svg
rm ./www/svg/cloud-circle-sharp.svg
rm ./www/svg/cloud-circle.svg
rm ./www/svg/cloud-done-outline.svg
rm ./www/svg/cloud-done-sharp.svg
rm ./www/svg/cloud-done.svg
rm ./www/svg/cloud-download-outline.svg
rm ./www/svg/cloud-download-sharp.svg
rm ./www/svg/cloud-download.svg
rm ./www/svg/cloud-offline-outline.svg
rm ./www/svg/cloud-offline-sharp.svg
rm ./www/svg/cloud-offline.svg
rm ./www/svg/cloud-outline.svg
rm ./www/svg/cloud-sharp.svg
rm ./www/svg/cloud-upload-outline.svg
rm ./www/svg/cloud-upload-sharp.svg
rm ./www/svg/cloud-upload.svg
rm ./www/svg/cloud.svg
rm ./www/svg/cloudy-night-outline.svg
rm ./www/svg/cloudy-night-sharp.svg
rm ./www/svg/cloudy-night.svg
rm ./www/svg/cloudy-outline.svg
rm ./www/svg/cloudy-sharp.svg
rm ./www/svg/cloudy.svg
rm ./www/svg/code-download-outline.svg
rm ./www/svg/code-download-sharp.svg
rm ./www/svg/code-download.svg
rm ./www/svg/code-outline.svg
rm ./www/svg/code-sharp.svg
rm ./www/svg/code-slash-outline.svg
rm ./www/svg/code-slash-sharp.svg
rm ./www/svg/code-slash.svg
rm ./www/svg/code-working-outline.svg
rm ./www/svg/code-working-sharp.svg
rm ./www/svg/code-working.svg
rm ./www/svg/code.svg
rm ./www/svg/cog-outline.svg
rm ./www/svg/cog-sharp.svg
rm ./www/svg/cog.svg
rm ./www/svg/color-fill-outline.svg
rm ./www/svg/color-fill-sharp.svg
rm ./www/svg/color-fill.svg
rm ./www/svg/color-filter-outline.svg
rm ./www/svg/color-filter-sharp.svg
rm ./www/svg/color-filter.svg
rm ./www/svg/color-palette-outline.svg
rm ./www/svg/color-palette-sharp.svg
rm ./www/svg/color-palette.svg
rm ./www/svg/color-wand-outline.svg
rm ./www/svg/color-wand-sharp.svg
rm ./www/svg/color-wand.svg
rm ./www/svg/compass-outline.svg
rm ./www/svg/compass-sharp.svg
rm ./www/svg/compass.svg
rm ./www/svg/construct-outline.svg
rm ./www/svg/construct-sharp.svg
rm ./www/svg/construct.svg
rm ./www/svg/contract-outline.svg
rm ./www/svg/contract-sharp.svg
rm ./www/svg/contract.svg
rm ./www/svg/contrast-outline.svg
rm ./www/svg/contrast-sharp.svg
rm ./www/svg/contrast.svg
rm ./www/svg/copy-outline.svg
rm ./www/svg/copy-sharp.svg
rm ./www/svg/copy.svg
rm ./www/svg/create-outline.svg
rm ./www/svg/create-sharp.svg
rm ./www/svg/create.svg
rm ./www/svg/crop-outline.svg
rm ./www/svg/crop-sharp.svg
rm ./www/svg/crop.svg
rm ./www/svg/cube-outline.svg
rm ./www/svg/cube-sharp.svg
rm ./www/svg/cube.svg
rm ./www/svg/cut-outline.svg
rm ./www/svg/cut-sharp.svg
rm ./www/svg/cut.svg
rm ./www/svg/desktop-outline.svg
rm ./www/svg/desktop-sharp.svg
rm ./www/svg/desktop.svg
rm ./www/svg/disc-outline.svg
rm ./www/svg/disc-sharp.svg
rm ./www/svg/disc.svg
rm ./www/svg/document-attach-outline.svg
rm ./www/svg/document-attach-sharp.svg
rm ./www/svg/document-attach.svg
rm ./www/svg/document-outline.svg
rm ./www/svg/document-sharp.svg
rm ./www/svg/document-text-outline.svg
rm ./www/svg/document-text-sharp.svg
rm ./www/svg/document-text.svg
rm ./www/svg/document.svg
rm ./www/svg/documents-outline.svg
rm ./www/svg/documents-sharp.svg
rm ./www/svg/documents.svg
rm ./www/svg/download-outline.svg
rm ./www/svg/download-sharp.svg
rm ./www/svg/download.svg
rm ./www/svg/duplicate-outline.svg
rm ./www/svg/duplicate-sharp.svg
rm ./www/svg/duplicate.svg
rm ./www/svg/ear-outline.svg
rm ./www/svg/ear-sharp.svg
rm ./www/svg/ear.svg
rm ./www/svg/earth-outline.svg
rm ./www/svg/earth-sharp.svg
rm ./www/svg/earth.svg
rm ./www/svg/easel-outline.svg
rm ./www/svg/easel-sharp.svg
rm ./www/svg/easel.svg
rm ./www/svg/egg-outline.svg
rm ./www/svg/egg-sharp.svg
rm ./www/svg/egg.svg
rm ./www/svg/ellipse-outline.svg
rm ./www/svg/ellipse-sharp.svg
rm ./www/svg/ellipse.svg
rm ./www/svg/ellipsis-horizontal-circle-outline.svg
rm ./www/svg/ellipsis-horizontal-circle-sharp.svg
rm ./www/svg/ellipsis-horizontal-circle.svg
rm ./www/svg/ellipsis-horizontal-outline.svg
rm ./www/svg/ellipsis-horizontal-sharp.svg
rm ./www/svg/ellipsis-horizontal.svg
rm ./www/svg/ellipsis-vertical-circle-outline.svg
rm ./www/svg/ellipsis-vertical-circle-sharp.svg
rm ./www/svg/ellipsis-vertical-circle.svg
rm ./www/svg/ellipsis-vertical-outline.svg
rm ./www/svg/ellipsis-vertical-sharp.svg
rm ./www/svg/ellipsis-vertical.svg
rm ./www/svg/enter-outline.svg
rm ./www/svg/enter-sharp.svg
rm ./www/svg/enter.svg
rm ./www/svg/exit-outline.svg
rm ./www/svg/exit-sharp.svg
rm ./www/svg/exit.svg
rm ./www/svg/expand-outline.svg
rm ./www/svg/expand-sharp.svg
rm ./www/svg/expand.svg
rm ./www/svg/eye-off-outline.svg
rm ./www/svg/eye-off-sharp.svg
rm ./www/svg/eye-off.svg
rm ./www/svg/eye-outline.svg
rm ./www/svg/eye-sharp.svg
rm ./www/svg/eye.svg
rm ./www/svg/eyedrop-outline.svg
rm ./www/svg/eyedrop-sharp.svg
rm ./www/svg/eyedrop.svg
rm ./www/svg/fast-food-outline.svg
rm ./www/svg/fast-food-sharp.svg
rm ./www/svg/fast-food.svg
rm ./www/svg/female-outline.svg
rm ./www/svg/female-sharp.svg
rm ./www/svg/female.svg
rm ./www/svg/file-tray-full-outline.svg
rm ./www/svg/file-tray-full-sharp.svg
rm ./www/svg/file-tray-full.svg
rm ./www/svg/file-tray-outline.svg
rm ./www/svg/file-tray-sharp.svg
rm ./www/svg/file-tray-stacked-outline.svg
rm ./www/svg/file-tray-stacked-sharp.svg
rm ./www/svg/file-tray-stacked.svg
rm ./www/svg/file-tray.svg
rm ./www/svg/film-outline.svg
rm ./www/svg/film-sharp.svg
rm ./www/svg/film.svg
rm ./www/svg/filter-outline.svg
rm ./www/svg/filter-sharp.svg
rm ./www/svg/filter.svg
rm ./www/svg/finger-print-outline.svg
rm ./www/svg/finger-print-sharp.svg
rm ./www/svg/finger-print.svg
rm ./www/svg/fitness-outline.svg
rm ./www/svg/fitness-sharp.svg
rm ./www/svg/fitness.svg
rm ./www/svg/flag-outline.svg
rm ./www/svg/flag-sharp.svg
rm ./www/svg/flag.svg
rm ./www/svg/flame-outline.svg
rm ./www/svg/flame-sharp.svg
rm ./www/svg/flame.svg
rm ./www/svg/flash-off-outline.svg
rm ./www/svg/flash-off-sharp.svg
rm ./www/svg/flash-off.svg
rm ./www/svg/flash-outline.svg
rm ./www/svg/flash-sharp.svg
rm ./www/svg/flash.svg
rm ./www/svg/flashlight-outline.svg
rm ./www/svg/flashlight-sharp.svg
rm ./www/svg/flashlight.svg
rm ./www/svg/flask-outline.svg
rm ./www/svg/flask-sharp.svg
rm ./www/svg/flask.svg
rm ./www/svg/flower-outline.svg
rm ./www/svg/flower-sharp.svg
rm ./www/svg/flower.svg
rm ./www/svg/folder-open-outline.svg
rm ./www/svg/folder-open-sharp.svg
rm ./www/svg/folder-open.svg
rm ./www/svg/folder-outline.svg
rm ./www/svg/folder-sharp.svg
rm ./www/svg/folder.svg
rm ./www/svg/football-outline.svg
rm ./www/svg/football-sharp.svg
rm ./www/svg/football.svg
rm ./www/svg/funnel-outline.svg
rm ./www/svg/funnel-sharp.svg
rm ./www/svg/funnel.svg
rm ./www/svg/game-controller-outline.svg
rm ./www/svg/game-controller-sharp.svg
rm ./www/svg/game-controller.svg
rm ./www/svg/gift-outline.svg
rm ./www/svg/gift-sharp.svg
rm ./www/svg/gift.svg
rm ./www/svg/git-branch-outline.svg
rm ./www/svg/git-branch-sharp.svg
rm ./www/svg/git-branch.svg
rm ./www/svg/git-commit-outline.svg
rm ./www/svg/git-commit-sharp.svg
rm ./www/svg/git-commit.svg
rm ./www/svg/git-compare-outline.svg
rm ./www/svg/git-compare-sharp.svg
rm ./www/svg/git-compare.svg
rm ./www/svg/git-merge-outline.svg
rm ./www/svg/git-merge-sharp.svg
rm ./www/svg/git-merge.svg
rm ./www/svg/git-network-outline.svg
rm ./www/svg/git-network-sharp.svg
rm ./www/svg/git-network.svg
rm ./www/svg/git-pull-request-outline.svg
rm ./www/svg/git-pull-request-sharp.svg
rm ./www/svg/git-pull-request.svg
rm ./www/svg/glasses-outline.svg
rm ./www/svg/glasses-sharp.svg
rm ./www/svg/glasses.svg
rm ./www/svg/globe-outline.svg
rm ./www/svg/globe-sharp.svg
rm ./www/svg/globe.svg
rm ./www/svg/golf-outline.svg
rm ./www/svg/golf-sharp.svg
rm ./www/svg/golf.svg
rm ./www/svg/grid-outline.svg
rm ./www/svg/grid-sharp.svg
rm ./www/svg/grid.svg
rm ./www/svg/hammer-outline.svg
rm ./www/svg/hammer-sharp.svg
rm ./www/svg/hammer.svg
rm ./www/svg/hand-left-outline.svg
rm ./www/svg/hand-left-sharp.svg
rm ./www/svg/hand-left.svg
rm ./www/svg/hand-right-outline.svg
rm ./www/svg/hand-right-sharp.svg
rm ./www/svg/hand-right.svg
rm ./www/svg/happy-outline.svg
rm ./www/svg/happy-sharp.svg
rm ./www/svg/happy.svg
rm ./www/svg/hardware-chip-outline.svg
rm ./www/svg/hardware-chip-sharp.svg
rm ./www/svg/hardware-chip.svg
rm ./www/svg/headset-outline.svg
rm ./www/svg/headset-sharp.svg
rm ./www/svg/headset.svg
rm ./www/svg/heart-circle-outline.svg
rm ./www/svg/heart-circle-sharp.svg
rm ./www/svg/heart-circle.svg
rm ./www/svg/heart-dislike-circle-outline.svg
rm ./www/svg/heart-dislike-circle-sharp.svg
rm ./www/svg/heart-dislike-circle.svg
rm ./www/svg/heart-dislike-outline.svg
rm ./www/svg/heart-dislike-sharp.svg
rm ./www/svg/heart-dislike.svg
rm ./www/svg/heart-half-outline.svg
rm ./www/svg/heart-half-sharp.svg
rm ./www/svg/heart-half.svg
rm ./www/svg/heart-outline.svg
rm ./www/svg/heart-sharp.svg
rm ./www/svg/heart.svg
rm ./www/svg/help-buoy-outline.svg
rm ./www/svg/help-buoy-sharp.svg
rm ./www/svg/help-buoy.svg
rm ./www/svg/help-circle-outline.svg
rm ./www/svg/help-circle-sharp.svg
rm ./www/svg/help-circle.svg
rm ./www/svg/help-outline.svg
rm ./www/svg/help-sharp.svg
rm ./www/svg/help.svg
rm ./www/svg/home-outline.svg
rm ./www/svg/home-sharp.svg
rm ./www/svg/home.svg
rm ./www/svg/hourglass-outline.svg
rm ./www/svg/hourglass-sharp.svg
rm ./www/svg/hourglass.svg
rm ./www/svg/ice-cream-outline.svg
rm ./www/svg/ice-cream-sharp.svg
rm ./www/svg/ice-cream.svg
rm ./www/svg/image-outline.svg
rm ./www/svg/image-sharp.svg
rm ./www/svg/image.svg
rm ./www/svg/images-outline.svg
rm ./www/svg/images-sharp.svg
rm ./www/svg/images.svg
rm ./www/svg/infinite-outline.svg
rm ./www/svg/infinite-sharp.svg
rm ./www/svg/infinite.svg
rm ./www/svg/information-circle-sharp.svg
rm ./www/svg/information-circle.svg
rm ./www/svg/information-outline.svg
rm ./www/svg/information-sharp.svg
rm ./www/svg/information.svg
rm ./www/svg/journal-outline.svg
rm ./www/svg/journal-sharp.svg
rm ./www/svg/journal.svg
rm ./www/svg/key-outline.svg
rm ./www/svg/key-sharp.svg
rm ./www/svg/key.svg
rm ./www/svg/keypad-outline.svg
rm ./www/svg/keypad-sharp.svg
rm ./www/svg/keypad.svg
rm ./www/svg/language-outline.svg
rm ./www/svg/language-sharp.svg
rm ./www/svg/language.svg
rm ./www/svg/laptop-outline.svg
rm ./www/svg/laptop-sharp.svg
rm ./www/svg/laptop.svg
rm ./www/svg/layers-outline.svg
rm ./www/svg/layers-sharp.svg
rm ./www/svg/layers.svg
rm ./www/svg/leaf-outline.svg
rm ./www/svg/leaf-sharp.svg
rm ./www/svg/leaf.svg
rm ./www/svg/library-outline.svg
rm ./www/svg/library-sharp.svg
rm ./www/svg/library.svg
rm ./www/svg/link-outline.svg
rm ./www/svg/link-sharp.svg
rm ./www/svg/link.svg
rm ./www/svg/list-circle-outline.svg
rm ./www/svg/list-circle-sharp.svg
rm ./www/svg/list-circle.svg
rm ./www/svg/list-outline.svg
rm ./www/svg/list-sharp.svg
rm ./www/svg/list.svg
rm ./www/svg/locate-outline.svg
rm ./www/svg/locate-sharp.svg
rm ./www/svg/locate.svg
rm ./www/svg/location-outline.svg
rm ./www/svg/location-sharp.svg
rm ./www/svg/location.svg
rm ./www/svg/lock-closed-outline.svg
rm ./www/svg/lock-closed-sharp.svg
rm ./www/svg/lock-closed.svg
rm ./www/svg/lock-open-outline.svg
rm ./www/svg/lock-open-sharp.svg
rm ./www/svg/lock-open.svg
rm ./www/svg/log-in-outline.svg
rm ./www/svg/log-in-sharp.svg
rm ./www/svg/log-in.svg
rm ./www/svg/log-out-outline.svg
rm ./www/svg/log-out-sharp.svg
rm ./www/svg/log-out.svg
rm ./www/svg/logo-amazon.svg
rm ./www/svg/logo-amplify.svg
rm ./www/svg/logo-android.svg
rm ./www/svg/logo-angular.svg
rm ./www/svg/logo-apple-appstore.svg
rm ./www/svg/logo-apple.svg
rm ./www/svg/logo-bitbucket.svg
rm ./www/svg/logo-bitcoin.svg
rm ./www/svg/logo-buffer.svg
rm ./www/svg/logo-capacitor.svg
rm ./www/svg/logo-chrome.svg
rm ./www/svg/logo-closed-captioning.svg
rm ./www/svg/logo-codepen.svg
rm ./www/svg/logo-css3.svg
rm ./www/svg/logo-designernews.svg
rm ./www/svg/logo-dribbble.svg
rm ./www/svg/logo-dropbox.svg
rm ./www/svg/logo-edge.svg
rm ./www/svg/logo-electron.svg
rm ./www/svg/logo-euro.svg
rm ./www/svg/logo-facebook.svg
rm ./www/svg/logo-firebase.svg
rm ./www/svg/logo-firefox.svg
rm ./www/svg/logo-flickr.svg
rm ./www/svg/logo-foursquare.svg
rm ./www/svg/logo-google-playstore.svg
rm ./www/svg/logo-google.svg
rm ./www/svg/logo-hackernews.svg
rm ./www/svg/logo-html5.svg
rm ./www/svg/logo-instagram.svg
rm ./www/svg/logo-ionic.svg
rm ./www/svg/logo-ionitron.svg
rm ./www/svg/logo-javascript.svg
rm ./www/svg/logo-laravel.svg
rm ./www/svg/logo-linkedin.svg
rm ./www/svg/logo-markdown.svg
rm ./www/svg/logo-no-smoking.svg
rm ./www/svg/logo-nodejs.svg
rm ./www/svg/logo-npm.svg
rm ./www/svg/logo-octocat.svg
rm ./www/svg/logo-pinterest.svg
rm ./www/svg/logo-playstation.svg
rm ./www/svg/logo-pwa.svg
rm ./www/svg/logo-python.svg
rm ./www/svg/logo-react.svg
rm ./www/svg/logo-reddit.svg
rm ./www/svg/logo-rss.svg
rm ./www/svg/logo-sass.svg
rm ./www/svg/logo-skype.svg
rm ./www/svg/logo-slack.svg
rm ./www/svg/logo-snapchat.svg
rm ./www/svg/logo-stackoverflow.svg
rm ./www/svg/logo-steam.svg
rm ./www/svg/logo-stencil.svg
rm ./www/svg/logo-tumblr.svg
rm ./www/svg/logo-tux.svg
rm ./www/svg/logo-twitch.svg
rm ./www/svg/logo-twitter.svg
rm ./www/svg/logo-usd.svg
rm ./www/svg/logo-vimeo.svg
rm ./www/svg/logo-vk.svg
rm ./www/svg/logo-vue.svg
rm ./www/svg/logo-web-component.svg
rm ./www/svg/logo-whatsapp.svg
rm ./www/svg/logo-windows.svg
rm ./www/svg/logo-wordpress.svg
rm ./www/svg/logo-xbox.svg
rm ./www/svg/logo-xing.svg
rm ./www/svg/logo-yahoo.svg
rm ./www/svg/logo-yen.svg
rm ./www/svg/logo-youtube.svg
rm ./www/svg/magnet-outline.svg
rm ./www/svg/magnet-sharp.svg
rm ./www/svg/magnet.svg
rm ./www/svg/mail-open-outline.svg
rm ./www/svg/mail-open-sharp.svg
rm ./www/svg/mail-open.svg
rm ./www/svg/mail-sharp.svg
rm ./www/svg/mail-unread-outline.svg
rm ./www/svg/mail-unread-sharp.svg
rm ./www/svg/mail-unread.svg
rm ./www/svg/mail.svg
rm ./www/svg/male-female-outline.svg
rm ./www/svg/male-female-sharp.svg
rm ./www/svg/male-female.svg
rm ./www/svg/male-outline.svg
rm ./www/svg/male-sharp.svg
rm ./www/svg/male.svg
rm ./www/svg/man-outline.svg
rm ./www/svg/man-sharp.svg
rm ./www/svg/man.svg
rm ./www/svg/map-outline.svg
rm ./www/svg/map-sharp.svg
rm ./www/svg/map.svg
rm ./www/svg/medal-outline.svg
rm ./www/svg/medal-sharp.svg
rm ./www/svg/medal.svg
rm ./www/svg/medical-outline.svg
rm ./www/svg/medical-sharp.svg
rm ./www/svg/medical.svg
rm ./www/svg/medkit-outline.svg
rm ./www/svg/medkit-sharp.svg
rm ./www/svg/medkit.svg
rm ./www/svg/megaphone-outline.svg
rm ./www/svg/megaphone-sharp.svg
rm ./www/svg/megaphone.svg
rm ./www/svg/mic-circle-outline.svg
rm ./www/svg/mic-circle-sharp.svg
rm ./www/svg/mic-circle.svg
rm ./www/svg/mic-off-circle-outline.svg
rm ./www/svg/mic-off-circle-sharp.svg
rm ./www/svg/mic-off-circle.svg
rm ./www/svg/mic-off-outline.svg
rm ./www/svg/mic-off-sharp.svg
rm ./www/svg/mic-off.svg
rm ./www/svg/mic-outline.svg
rm ./www/svg/mic-sharp.svg
rm ./www/svg/mic.svg
rm ./www/svg/moon-outline.svg
rm ./www/svg/moon-sharp.svg
rm ./www/svg/moon.svg
rm ./www/svg/move-outline.svg
rm ./www/svg/move-sharp.svg
rm ./www/svg/move.svg
rm ./www/svg/musical-note-outline.svg
rm ./www/svg/musical-note-sharp.svg
rm ./www/svg/musical-note.svg
rm ./www/svg/musical-notes-outline.svg
rm ./www/svg/musical-notes-sharp.svg
rm ./www/svg/musical-notes.svg
rm ./www/svg/navigate-circle-outline.svg
rm ./www/svg/navigate-circle-sharp.svg
rm ./www/svg/navigate-circle.svg
rm ./www/svg/navigate-outline.svg
rm ./www/svg/navigate-sharp.svg
rm ./www/svg/navigate.svg
rm ./www/svg/newspaper-outline.svg
rm ./www/svg/newspaper-sharp.svg
rm ./www/svg/newspaper.svg
rm ./www/svg/notifications-circle-outline.svg
rm ./www/svg/notifications-circle-sharp.svg
rm ./www/svg/notifications-circle.svg
rm ./www/svg/notifications-off-circle-outline.svg
rm ./www/svg/notifications-off-circle-sharp.svg
rm ./www/svg/notifications-off-circle.svg
rm ./www/svg/notifications-off-outline.svg
rm ./www/svg/notifications-off-sharp.svg
rm ./www/svg/notifications-off.svg
rm ./www/svg/notifications-outline.svg
rm ./www/svg/notifications-sharp.svg
rm ./www/svg/notifications.svg
rm ./www/svg/nuclear-outline.svg
rm ./www/svg/nuclear-sharp.svg
rm ./www/svg/nuclear.svg
rm ./www/svg/nutrition-outline.svg
rm ./www/svg/nutrition-sharp.svg
rm ./www/svg/nutrition.svg
rm ./www/svg/open-outline.svg
rm ./www/svg/open-sharp.svg
rm ./www/svg/open.svg
rm ./www/svg/options-outline.svg
rm ./www/svg/options-sharp.svg
rm ./www/svg/options.svg
rm ./www/svg/paper-plane-outline.svg
rm ./www/svg/paper-plane-sharp.svg
rm ./www/svg/paper-plane.svg
rm ./www/svg/partly-sunny-outline.svg
rm ./www/svg/partly-sunny-sharp.svg
rm ./www/svg/partly-sunny.svg
rm ./www/svg/pause-circle-outline.svg
rm ./www/svg/pause-circle-sharp.svg
rm ./www/svg/pause-circle.svg
rm ./www/svg/pause-outline.svg
rm ./www/svg/pause-sharp.svg
rm ./www/svg/pause.svg
rm ./www/svg/paw-outline.svg
rm ./www/svg/paw-sharp.svg
rm ./www/svg/paw.svg
rm ./www/svg/pencil-outline.svg
rm ./www/svg/pencil-sharp.svg
rm ./www/svg/pencil.svg
rm ./www/svg/people-circle-outline.svg
rm ./www/svg/people-circle-sharp.svg
rm ./www/svg/people-circle.svg
rm ./www/svg/people-outline.svg
rm ./www/svg/people-sharp.svg
rm ./www/svg/people.svg
rm ./www/svg/person-add-outline.svg
rm ./www/svg/person-add-sharp.svg
rm ./www/svg/person-add.svg
rm ./www/svg/person-circle-outline.svg
rm ./www/svg/person-circle-sharp.svg
rm ./www/svg/person-circle.svg
rm ./www/svg/person-outline.svg
rm ./www/svg/person-remove-outline.svg
rm ./www/svg/person-remove-sharp.svg
rm ./www/svg/person-remove.svg
rm ./www/svg/person-sharp.svg
rm ./www/svg/person.svg
rm ./www/svg/phone-landscape-outline.svg
rm ./www/svg/phone-landscape-sharp.svg
rm ./www/svg/phone-landscape.svg
rm ./www/svg/phone-portrait-outline.svg
rm ./www/svg/phone-portrait-sharp.svg
rm ./www/svg/phone-portrait.svg
rm ./www/svg/pie-chart-outline.svg
rm ./www/svg/pie-chart-sharp.svg
rm ./www/svg/pie-chart.svg
rm ./www/svg/pin-outline.svg
rm ./www/svg/pin-sharp.svg
rm ./www/svg/pin.svg
rm ./www/svg/pint-outline.svg
rm ./www/svg/pint-sharp.svg
rm ./www/svg/pint.svg
rm ./www/svg/pizza-outline.svg
rm ./www/svg/pizza-sharp.svg
rm ./www/svg/pizza.svg
rm ./www/svg/planet-outline.svg
rm ./www/svg/planet-sharp.svg
rm ./www/svg/planet.svg
rm ./www/svg/play-back-circle-outline.svg
rm ./www/svg/play-back-circle-sharp.svg
rm ./www/svg/play-back-circle.svg
rm ./www/svg/play-back-outline.svg
rm ./www/svg/play-back-sharp.svg
rm ./www/svg/play-back.svg
rm ./www/svg/play-circle-outline.svg
rm ./www/svg/play-circle-sharp.svg
rm ./www/svg/play-circle.svg
rm ./www/svg/play-forward-circle-outline.svg
rm ./www/svg/play-forward-circle-sharp.svg
rm ./www/svg/play-forward-circle.svg
rm ./www/svg/play-forward-outline.svg
rm ./www/svg/play-forward-sharp.svg
rm ./www/svg/play-forward.svg
rm ./www/svg/play-outline.svg
rm ./www/svg/play-sharp.svg
rm ./www/svg/play-skip-back-circle-outline.svg
rm ./www/svg/play-skip-back-circle-sharp.svg
rm ./www/svg/play-skip-back-circle.svg
rm ./www/svg/play-skip-back-outline.svg
rm ./www/svg/play-skip-back-sharp.svg
rm ./www/svg/play-skip-back.svg
rm ./www/svg/play-skip-forward-circle-outline.svg
rm ./www/svg/play-skip-forward-circle-sharp.svg
rm ./www/svg/play-skip-forward-circle.svg
rm ./www/svg/play-skip-forward-outline.svg
rm ./www/svg/play-skip-forward-sharp.svg
rm ./www/svg/play-skip-forward.svg
rm ./www/svg/play.svg
rm ./www/svg/podium-outline.svg
rm ./www/svg/podium-sharp.svg
rm ./www/svg/podium.svg
rm ./www/svg/power-outline.svg
rm ./www/svg/power-sharp.svg
rm ./www/svg/power.svg
rm ./www/svg/pricetag-outline.svg
rm ./www/svg/pricetag-sharp.svg
rm ./www/svg/pricetag.svg
rm ./www/svg/pricetags-outline.svg
rm ./www/svg/pricetags-sharp.svg
rm ./www/svg/pricetags.svg
rm ./www/svg/print-outline.svg
rm ./www/svg/print-sharp.svg
rm ./www/svg/print.svg
rm ./www/svg/pulse-outline.svg
rm ./www/svg/pulse-sharp.svg
rm ./www/svg/pulse.svg
rm ./www/svg/push-outline.svg
rm ./www/svg/push-sharp.svg
rm ./www/svg/push.svg
rm ./www/svg/qr-code-outline.svg
rm ./www/svg/qr-code-sharp.svg
rm ./www/svg/qr-code.svg
rm ./www/svg/radio-button-off-outline.svg
rm ./www/svg/radio-button-off-sharp.svg
rm ./www/svg/radio-button-off.svg
rm ./www/svg/radio-button-on-outline.svg
rm ./www/svg/radio-button-on-sharp.svg
rm ./www/svg/radio-button-on.svg
rm ./www/svg/radio-outline.svg
rm ./www/svg/radio-sharp.svg
rm ./www/svg/radio.svg
rm ./www/svg/rainy-outline.svg
rm ./www/svg/rainy-sharp.svg
rm ./www/svg/rainy.svg
rm ./www/svg/reader-outline.svg
rm ./www/svg/reader-sharp.svg
rm ./www/svg/reader.svg
rm ./www/svg/receipt-outline.svg
rm ./www/svg/receipt-sharp.svg
rm ./www/svg/receipt.svg
rm ./www/svg/recording-outline.svg
rm ./www/svg/recording-sharp.svg
rm ./www/svg/recording.svg
rm ./www/svg/refresh-circle-outline.svg
rm ./www/svg/refresh-circle-sharp.svg
rm ./www/svg/refresh-circle.svg
rm ./www/svg/refresh-outline.svg
rm ./www/svg/refresh-sharp.svg
rm ./www/svg/refresh.svg
rm ./www/svg/reload-circle-outline.svg
rm ./www/svg/reload-circle-sharp.svg
rm ./www/svg/reload-circle.svg
rm ./www/svg/reload-outline.svg
rm ./www/svg/reload-sharp.svg
rm ./www/svg/reload.svg
rm ./www/svg/remove-circle-outline.svg
rm ./www/svg/remove-circle-sharp.svg
rm ./www/svg/remove-circle.svg
rm ./www/svg/remove-outline.svg
rm ./www/svg/remove-sharp.svg
rm ./www/svg/remove.svg
rm ./www/svg/reorder-four-outline.svg
rm ./www/svg/reorder-four-sharp.svg
rm ./www/svg/reorder-four.svg
rm ./www/svg/reorder-three-outline.svg
rm ./www/svg/reorder-three-sharp.svg
rm ./www/svg/reorder-three.svg
rm ./www/svg/reorder-two-outline.svg
rm ./www/svg/reorder-two-sharp.svg
rm ./www/svg/reorder-two.svg
rm ./www/svg/repeat-outline.svg
rm ./www/svg/repeat-sharp.svg
rm ./www/svg/repeat.svg
rm ./www/svg/resize-outline.svg
rm ./www/svg/resize-sharp.svg
rm ./www/svg/resize.svg
rm ./www/svg/restaurant-outline.svg
rm ./www/svg/restaurant-sharp.svg
rm ./www/svg/restaurant.svg
rm ./www/svg/return-down-back-outline.svg
rm ./www/svg/return-down-back-sharp.svg
rm ./www/svg/return-down-back.svg
rm ./www/svg/return-down-forward-outline.svg
rm ./www/svg/return-down-forward-sharp.svg
rm ./www/svg/return-down-forward.svg
rm ./www/svg/return-up-back-outline.svg
rm ./www/svg/return-up-back-sharp.svg
rm ./www/svg/return-up-back.svg
rm ./www/svg/return-up-forward-outline.svg
rm ./www/svg/return-up-forward-sharp.svg
rm ./www/svg/return-up-forward.svg
rm ./www/svg/ribbon-outline.svg
rm ./www/svg/ribbon-sharp.svg
rm ./www/svg/ribbon.svg
rm ./www/svg/rocket-outline.svg
rm ./www/svg/rocket-sharp.svg
rm ./www/svg/rocket.svg
rm ./www/svg/rose-outline.svg
rm ./www/svg/rose-sharp.svg
rm ./www/svg/rose.svg
rm ./www/svg/sad-outline.svg
rm ./www/svg/sad-sharp.svg
rm ./www/svg/sad.svg
rm ./www/svg/save-outline.svg
rm ./www/svg/save-sharp.svg
rm ./www/svg/save.svg
rm ./www/svg/scan-circle-outline.svg
rm ./www/svg/scan-circle-sharp.svg
rm ./www/svg/scan-circle.svg
rm ./www/svg/scan-outline.svg
rm ./www/svg/scan-sharp.svg
rm ./www/svg/scan.svg
rm ./www/svg/school-outline.svg
rm ./www/svg/school-sharp.svg
rm ./www/svg/school.svg
rm ./www/svg/search-circle-outline.svg
rm ./www/svg/search-circle-sharp.svg
rm ./www/svg/search-circle.svg
rm ./www/svg/search-sharp.svg
rm ./www/svg/search.svg
rm ./www/svg/send-outline.svg
rm ./www/svg/send-sharp.svg
rm ./www/svg/send.svg
rm ./www/svg/server-outline.svg
rm ./www/svg/server-sharp.svg
rm ./www/svg/server.svg
rm ./www/svg/settings-outline.svg
rm ./www/svg/settings-sharp.svg
rm ./www/svg/settings.svg
rm ./www/svg/shapes-outline.svg
rm ./www/svg/shapes-sharp.svg
rm ./www/svg/shapes.svg
rm ./www/svg/share-outline.svg
rm ./www/svg/share-sharp.svg
rm ./www/svg/share-social-outline.svg
rm ./www/svg/share-social-sharp.svg
rm ./www/svg/share-social.svg
rm ./www/svg/share.svg
rm ./www/svg/shield-checkmark-outline.svg
rm ./www/svg/shield-checkmark-sharp.svg
rm ./www/svg/shield-checkmark.svg
rm ./www/svg/shield-outline.svg
rm ./www/svg/shield-sharp.svg
rm ./www/svg/shield.svg
rm ./www/svg/shirt-outline.svg
rm ./www/svg/shirt-sharp.svg
rm ./www/svg/shirt.svg
rm ./www/svg/shuffle-outline.svg
rm ./www/svg/shuffle-sharp.svg
rm ./www/svg/shuffle.svg
rm ./www/svg/skull-outline.svg
rm ./www/svg/skull-sharp.svg
rm ./www/svg/skull.svg
rm ./www/svg/snow-outline.svg
rm ./www/svg/snow-sharp.svg
rm ./www/svg/snow.svg
rm ./www/svg/speedometer-outline.svg
rm ./www/svg/speedometer-sharp.svg
rm ./www/svg/speedometer.svg
rm ./www/svg/square-outline.svg
rm ./www/svg/square-sharp.svg
rm ./www/svg/square.svg
rm ./www/svg/star-half-outline.svg
rm ./www/svg/star-half-sharp.svg
rm ./www/svg/star-half.svg
rm ./www/svg/star-outline.svg
rm ./www/svg/star-sharp.svg
rm ./www/svg/star.svg
rm ./www/svg/stats-chart-outline.svg
rm ./www/svg/stats-chart-sharp.svg
rm ./www/svg/stats-chart.svg
rm ./www/svg/stop-circle-outline.svg
rm ./www/svg/stop-circle-sharp.svg
rm ./www/svg/stop-circle.svg
rm ./www/svg/stop-outline.svg
rm ./www/svg/stop-sharp.svg
rm ./www/svg/stop.svg
rm ./www/svg/stopwatch-outline.svg
rm ./www/svg/stopwatch-sharp.svg
rm ./www/svg/stopwatch.svg
rm ./www/svg/subway-outline.svg
rm ./www/svg/subway-sharp.svg
rm ./www/svg/subway.svg
rm ./www/svg/sunny-outline.svg
rm ./www/svg/sunny-sharp.svg
rm ./www/svg/sunny.svg
rm ./www/svg/swap-horizontal-outline.svg
rm ./www/svg/swap-horizontal-sharp.svg
rm ./www/svg/swap-horizontal.svg
rm ./www/svg/swap-vertical-outline.svg
rm ./www/svg/swap-vertical-sharp.svg
rm ./www/svg/swap-vertical.svg
rm ./www/svg/sync-circle-outline.svg
rm ./www/svg/sync-circle-sharp.svg
rm ./www/svg/sync-circle.svg
rm ./www/svg/sync-outline.svg
rm ./www/svg/sync-sharp.svg
rm ./www/svg/sync.svg
rm ./www/svg/tablet-landscape-outline.svg
rm ./www/svg/tablet-landscape-sharp.svg
rm ./www/svg/tablet-landscape.svg
rm ./www/svg/tablet-portrait-outline.svg
rm ./www/svg/tablet-portrait-sharp.svg
rm ./www/svg/tablet-portrait.svg
rm ./www/svg/tennisball-outline.svg
rm ./www/svg/tennisball-sharp.svg
rm ./www/svg/tennisball.svg
rm ./www/svg/terminal-outline.svg
rm ./www/svg/terminal-sharp.svg
rm ./www/svg/terminal.svg
rm ./www/svg/text-outline.svg
rm ./www/svg/text-sharp.svg
rm ./www/svg/text.svg
rm ./www/svg/thermometer-outline.svg
rm ./www/svg/thermometer-sharp.svg
rm ./www/svg/thermometer.svg
rm ./www/svg/thumbs-down-outline.svg
rm ./www/svg/thumbs-down-sharp.svg
rm ./www/svg/thumbs-down.svg
rm ./www/svg/thumbs-up-outline.svg
rm ./www/svg/thumbs-up-sharp.svg
rm ./www/svg/thumbs-up.svg
rm ./www/svg/thunderstorm-outline.svg
rm ./www/svg/thunderstorm-sharp.svg
rm ./www/svg/thunderstorm.svg
rm ./www/svg/time-outline.svg
rm ./www/svg/time-sharp.svg
rm ./www/svg/time.svg
rm ./www/svg/timer-outline.svg
rm ./www/svg/timer-sharp.svg
rm ./www/svg/timer.svg
rm ./www/svg/today-outline.svg
rm ./www/svg/today-sharp.svg
rm ./www/svg/today.svg
rm ./www/svg/toggle-outline.svg
rm ./www/svg/toggle-sharp.svg
rm ./www/svg/toggle.svg
rm ./www/svg/trail-sign-outline.svg
rm ./www/svg/trail-sign-sharp.svg
rm ./www/svg/trail-sign.svg
rm ./www/svg/train-outline.svg
rm ./www/svg/train-sharp.svg
rm ./www/svg/train.svg
rm ./www/svg/transgender-outline.svg
rm ./www/svg/transgender-sharp.svg
rm ./www/svg/transgender.svg
rm ./www/svg/trash-bin-outline.svg
rm ./www/svg/trash-bin-sharp.svg
rm ./www/svg/trash-bin.svg
rm ./www/svg/trash-outline.svg
rm ./www/svg/trash-sharp.svg
rm ./www/svg/trash.svg
rm ./www/svg/trending-down-outline.svg
rm ./www/svg/trending-down-sharp.svg
rm ./www/svg/trending-down.svg
rm ./www/svg/trending-up-outline.svg
rm ./www/svg/trending-up-sharp.svg
rm ./www/svg/trending-up.svg
rm ./www/svg/triangle-outline.svg
rm ./www/svg/triangle-sharp.svg
rm ./www/svg/triangle.svg
rm ./www/svg/trophy-outline.svg
rm ./www/svg/trophy-sharp.svg
rm ./www/svg/trophy.svg
rm ./www/svg/tv-outline.svg
rm ./www/svg/tv-sharp.svg
rm ./www/svg/tv.svg
rm ./www/svg/umbrella-outline.svg
rm ./www/svg/umbrella-sharp.svg
rm ./www/svg/umbrella.svg
rm ./www/svg/videocam-outline.svg
rm ./www/svg/videocam-sharp.svg
rm ./www/svg/videocam.svg
rm ./www/svg/volume-high-outline.svg
rm ./www/svg/volume-high-sharp.svg
rm ./www/svg/volume-high.svg
rm ./www/svg/volume-low-outline.svg
rm ./www/svg/volume-low-sharp.svg
rm ./www/svg/volume-low.svg
rm ./www/svg/volume-medium-outline.svg
rm ./www/svg/volume-medium-sharp.svg
rm ./www/svg/volume-medium.svg
rm ./www/svg/volume-mute-outline.svg
rm ./www/svg/volume-mute-sharp.svg
rm ./www/svg/volume-mute.svg
rm ./www/svg/volume-off-outline.svg
rm ./www/svg/volume-off-sharp.svg
rm ./www/svg/volume-off.svg
rm ./www/svg/walk-outline.svg
rm ./www/svg/walk-sharp.svg
rm ./www/svg/walk.svg
rm ./www/svg/wallet-outline.svg
rm ./www/svg/wallet-sharp.svg
rm ./www/svg/wallet.svg
rm ./www/svg/warning-sharp.svg
rm ./www/svg/warning.svg
rm ./www/svg/watch-outline.svg
rm ./www/svg/watch-sharp.svg
rm ./www/svg/watch.svg
rm ./www/svg/water-outline.svg
rm ./www/svg/water-sharp.svg
rm ./www/svg/water.svg
rm ./www/svg/wifi-outline.svg
rm ./www/svg/wifi-sharp.svg
rm ./www/svg/wifi.svg
rm ./www/svg/wine-outline.svg
rm ./www/svg/wine-sharp.svg
rm ./www/svg/wine.svg
rm ./www/svg/woman-outline.svg
rm ./www/svg/woman-sharp.svg
rm ./www/svg/woman.svg
